### ISSUE TITLE
突然无法运行

### ISSUE THREAD

**Issue by donydex** [MichealWayne/FundCharts#1]
感觉似乎是版本更新问题
之前保存的所有可以运行的画折线图的版本，现在都报以下错误
确认画图代码无改动

Cannot read property 'x' of undefined;at pages/blood/index page drawLine function
TypeError: Cannot read property 'x' of undefined

**Comment by MichealWayne** [comment]
已收到您的反馈，可否麻烦将折线图的配置项及数据结构复制或截图，并发送给michealwayne@163.com。谢谢
