### ISSUE TITLE
折线图的轴线怎么弄出来?

### ISSUE THREAD

**Issue by tuxmxm** [MichealWayne/FundCharts#2]
折线图的轴线怎么弄出来?

**Comment by MichealWayne** [comment]
移动端默认带有一像素#999的纵轴线（小程序需绑定wxml容器touch事件，可见[demo-line](https://github.com/MichealWayne/FundCharts/tree/master/demo/weapp/line)），pc端需手动在[配置项events](http://blog.michealwayne.cn/FundCharts/docs/graphs/#%E5%AE%9E%E4%BE%8B%E5%8C%96)中添加pc事件后也会带有纵轴线，如`events: ['mousemove']`。
横轴线需手动添加。

**Comment by tuxmxm** [comment]
我指的是那两条固定的轴线（x轴与y轴），小程序是没有的，看起来觉得怪怪的，建议还是要有（或者自定义）

**Comment by MichealWayne** [comment]
好的了解，下期0.9.3将增加这两个轴线的控制，现有版本可通过onAnimation或onFinish用画布绘制，如
``` js
// options...
onAnimation () {
		let ctx = chart1.ctx,   // chart1为实例
			opts = chart1.opts,
			width = chart1._chart.width,
			height = chart1._chart.height;
		
		ctx.moveTo(opts.chartLeft, height - 25);
		ctx.lineTo(opts.chartLeft, opts.chartTop);
		ctx.stroke();
		
		ctx.moveTo(opts.chartLeft, height - 25);
		ctx.lineTo(width - opts.chartRight, height - 25);
		ctx.stroke();
	}
// ...
```
