### ISSUE TITLE
使用Vue组件在同一页面渲染多个相同组件id问题

### ISSUE THREAD

**Issue by zhenyu-dev** [MichealWayne/FundCharts#3]
使用vue组件渲染折线图
折线图组件如下
`<v-line
    v-if="isChartVisible"
    :options="options"
    class="lineId"
    :style="setHeight"
  />`

`
options() {
      return {
        colors: ["#E8302E", "#007AFF"],
        yaxisfunc: (data) => {
          return data.toFixed(2) + "%";
        },
        hover: this.handleHover,
        dash: {
          isSolid: true
        },
        font: {
          color: '#A3A3A3',
          fontSize: {
            x: '12px',
            y: '10px'
          }
        },
        ...this.lineData,
      }
    }
`
lineData是传进组件的 datas 和 xaxis数据

在同一页面渲染多个该组件，查看element面板，发现id是相同的，导致更新某个图标数据会导致该图表空白，并且其他图表改变，感觉问题就出id重复，尝试着在options里写id（id不会应用），在组件上直接覆盖id（会导致找不到context）都不行，源码也没开源，我们应该是同一个公司的，请问该怎么解决

**Comment by MichealWayne** [comment]
可以通过设置prefix属性进行id控制，如
`<v-line prefix="chart1" v-if="isCh...... />`
感谢你的提出，后续会优化vue/react使用文档 :smile: 
ps: 预期1.x版本会开源

**Comment by zhenyu-dev** [comment]
prefix解决了:thumbsup:
